version: "3"

services:

  postgres:
    image: postgres:14.5-alpine
    container_name: editor
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: image-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 132
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  minio-data: