version: "3"

services:
  api:
    image: 'necute_boy/api:1.0.0'
    container_name: 'image-api'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - 'postgres'
      - 'minio'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://editor:5432/image-project'
      - 'MINIO_URL=http://image-minio:9000'

  postgres:
    image: postgres:14.5-alpine
    container_name: editor
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: image-project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 132
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - db-data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: 'image-minio'
    environment:
      - 'MINIO_ROOT_USER=user'
      - 'MINIO_ROOT_PASSWORD=password'
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001

volumes:
  db-data:
  minio-data: